/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.scuffedsoftware.studybomb;
import java.io.File;
import javax.swing.text.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.*;
import java.awt.font.TextAttribute;
import java.util.Map;
import java.util.HashMap;


class timerFilter extends DocumentFilter {
    
    private boolean filter(String text) {
        //If the string is not an integer, return false.
        if (text.matches("[0-9]+")) {
            return true;
        } else {
            return false;
        }
    }
    
    @Override
    public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) 
            throws BadLocationException {
        Document doc = fb.getDocument();
        StringBuilder timerText = new StringBuilder();
        timerText.append(doc.getText(0,doc.getLength()));
        
        if (filter(timerText.toString())) {
            super.insertString(fb, offset, string, attr);
            if (timerText.length() <= 8) {
                super.remove(fb, 0, 1);
            if (timerText.length() < 8) {
                super.insertString(fb, 0, string,attr);
                }
            }
        } else {
            Toolkit.getDefaultToolkit().beep();
        }
    }
    
    @Override
       public void replace(FilterBypass fb, int offset, int length, String text, 
               AttributeSet attrs) throws BadLocationException {

      Document doc = fb.getDocument();
      StringBuilder timerText = new StringBuilder();
      timerText.append(doc.getText(0, doc.getLength()));
      timerText.replace(offset, offset + length, text);

      //If filter returns true, allow replacement. If too few characters exist,
      //...initiate removal.
      if (filter(timerText.toString())) {
         super.replace(fb, offset, length, text, attrs); //TODO: fix dis
            if (timerText.length() <= 7) {
                super.remove(fb, 0, 1);
            }
            if (timerText.length() < 7) {
                //If the character at the start is 0, insert 0. 
                //if NOT, replace the string with whatever was in the first slot
                super.insertString(fb, 0, timerText.substring(0, 1),null);
                }
      } else {
         // nothing! :)
      }
   }
       
   @Override
   public void remove(FilterBypass fb, int offset, int length)
         throws BadLocationException {
      Document doc = fb.getDocument();
      StringBuilder sb = new StringBuilder();
      sb.append(doc.getText(0, doc.getLength()));
      sb.delete(offset, offset + length);
      
      if (filter(sb.toString())) {
         super.remove(fb, offset, length);
         super.insertString(fb, 0, "0",null);
      } else {
         // nothing! :)
      }
   }
}

final class DeleteAssist { 
    private File target;
    
    public static void kaboom(File target) {
        System.out.println("FAREWELL, BOYE!");
        target.delete();
    }
    
}
/**
 *
 * @author Ismael Fuentes
 */
public class StudyBomb extends javax.swing.JFrame {
    private File fileTarget;
    
    /**
     * Creates new form StudyBombGUI
     */
    public StudyBomb() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        timerDialog = new javax.swing.JFrame();
        fileExplorer = new javax.swing.JFileChooser();
        timerPanel = new javax.swing.JPanel();
        timerUI = new javax.swing.JLabel();
        timerRuler = new javax.swing.JLabel();
        timerInput = new javax.swing.JTextField();
        Font timerFont = new Font("Helvetica Neue",0,68);
        Map<TextAttribute,Object> attributes = new HashMap<TextAttribute,Object>();
        attributes.put(TextAttribute.TRACKING, 0.3);
        timerFont = timerFont.deriveFont(attributes);
        filterGUISetup(); //Assigns DocumentFilters to input field
        timerDisplay = new javax.swing.JLabel();
        timerControls = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        filePanel = new javax.swing.JPanel();
        fileSearchButton = new javax.swing.JButton();
        fileLabel = new javax.swing.JLabel();
        taskView = new javax.swing.JLayeredPane();
        taskAddButton = new javax.swing.JButton();
        taskScroll = new javax.swing.JScrollPane();
        taskPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout timerDialogLayout = new javax.swing.GroupLayout(timerDialog.getContentPane());
        timerDialog.getContentPane().setLayout(timerDialogLayout);
        timerDialogLayout.setHorizontalGroup(
            timerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        timerDialogLayout.setVerticalGroup(
            timerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        fileExplorer.setApproveButtonText("Select");
        fileExplorer.setApproveButtonToolTipText("Selects this file as a target.");
        fileExplorer.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StudyBomb");
        setAutoRequestFocus(false);
        setResizable(false);

        timerPanel.setLayout(null);

        timerUI.setFont(new java.awt.Font("Helvetica Neue", 0, 68)); // NOI18N
        timerUI.setText("    :     : ");
        timerPanel.add(timerUI);
        timerUI.setBounds(30, 20, 350, 60);

        timerRuler.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        timerRuler.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timerRuler.setText("h              m              s");
        timerRuler.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        timerRuler.setAlignmentY(1.0F);
        timerRuler.setFocusable(false);
        timerPanel.add(timerRuler);
        timerRuler.setBounds(110, 71, 340, 29);

        timerInput.setBackground(new java.awt.Color(204, 204, 204));
        timerInput.setFont(timerFont);
        timerInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        timerInput.setText("000000");
        timerInput.setBorder(null);
        timerInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timerInputMouseClicked(evt);
            }
        });
        timerPanel.add(timerInput);
        timerInput.setBounds(0, 0, 370, 103);

        timerDisplay.setFont(timerFont);
        timerDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerDisplay.setText("000000");
        timerDisplay.setEnabled(false);
        timerPanel.add(timerDisplay);
        timerDisplay.setBounds(10, 20, 350, 60);

        timerControls.setLayout(new java.awt.CardLayout());

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        timerControls.add(startButton, "card3");

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        timerControls.add(stopButton, "card2");

        filePanel.setLayout(new javax.swing.BoxLayout(filePanel, javax.swing.BoxLayout.LINE_AXIS));

        fileSearchButton.setText("Select");
        fileSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSearchButtonActionPerformed(evt);
            }
        });
        filePanel.add(fileSearchButton);

        fileLabel.setText("Choose a file...");
        filePanel.add(fileLabel);

        taskAddButton.setText("+");
        taskAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskAddButtonActionPerformed(evt);
            }
        });

        taskPanel.setRequestFocusEnabled(false);
        taskPanel.setLayout(new javax.swing.BoxLayout(taskPanel, javax.swing.BoxLayout.PAGE_AXIS));
        taskScroll.setViewportView(taskPanel);

        taskView.setLayer(taskAddButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        taskView.setLayer(taskScroll, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout taskViewLayout = new javax.swing.GroupLayout(taskView);
        taskView.setLayout(taskViewLayout);
        taskViewLayout.setHorizontalGroup(
            taskViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
            .addGroup(taskViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(taskViewLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(taskScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        taskViewLayout.setVerticalGroup(
            taskViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(taskAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(taskViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(taskViewLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(taskScroll)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(timerControls, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(taskView, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 300, Short.MAX_VALUE)
                        .addComponent(filePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timerControls, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSearchButtonActionPerformed
        // TODO add your handling code here:
        int userChoice = fileExplorer.showOpenDialog(this);
        if (userChoice == JFileChooser.APPROVE_OPTION) {
            this.fileTarget = fileExplorer.getSelectedFile();
            fileLabel.setText(fileTarget.getPath());
        }
    }//GEN-LAST:event_fileSearchButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed

        int userChoice = JOptionPane.showConfirmDialog(timerDialog,
                "Please note that I wasn't joking about deleting your files. \n\n"
                        + "**I will actually delete them. They will be unrecoverable.**\n\n"
                        + "These files will delete once your allotted time is up. "
                        + "After 20% of your time has passed, you can opt to cancel early. \n"
                        + "I take no responsibility for damage caused by any lost files.\n"
                        + "Before you begin, ensure you have enough time without outside interference."
                        + "Would you like to continue? Accepting will instantly start the timer.",
                "Warning",JOptionPane.YES_NO_OPTION);
        switch (userChoice) {
            case JOptionPane.YES_OPTION:
                if (fileTarget == null) {
                    JOptionPane.showMessageDialog(timerDialog,"No file has been selected.");
                    break;
                } else {
                timerInput.setVisible(false);
                timerInput.setEnabled(false);
                timerDisplay.setEnabled(true);
                timerDisplay.setText(timerInput.getText());
                
                
                startButton.setVisible(false);
                startButton.setEnabled(false);
                stopButton.setVisible(true);
                stopButton.setEnabled(true);
                taskAddButton.setEnabled(false);
                //TODO: Once I figure out CardLayout, rewrite this. it's ugly and makes me cry
                //by extension, rewrite this whole thing. it is UGLY
                
                for (ActionListener task : startButton.getActionListeners()) {
                    if ((task.getClass().getName().equals("com.scuffedsoftware.studybomb.Task$6")))
                    task.actionPerformed(new ActionEvent(startButton, ActionEvent.ACTION_PERFORMED, null) { //Locks the tasks, making them uneditable
                    });
                }
                
                TimerAssist.timerStart(timerDisplay.getText(),timerDisplay, fileTarget); //starts the timer
                break;
                }
            case JOptionPane.NO_OPTION:
                break;
        //
            default:
                break;
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        TimerAssist.timerStop();
        JOptionPane.showMessageDialog(timerDialog,"Coward.");
        
        
        timerInput.setVisible(true);
        timerInput.setEnabled(true);
        timerDisplay.setEnabled(false);
        timerDisplay.setText("000000");
                
        startButton.setVisible(true);
        startButton.setEnabled(true);
        stopButton.setVisible(false);
        stopButton.setEnabled(false);
        taskAddButton.setEnabled(true);
        //TODO: make this look better someday, it makes my eyes water
        
    }//GEN-LAST:event_stopButtonActionPerformed

    private void timerInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timerInputMouseClicked
// corrects user input if the minute/second counter exceeds 59
    StringBuilder timerTextEdit = new StringBuilder(timerInput.getText());
    
    if (Integer.parseInt(timerTextEdit.substring(2,4)) > 59) {
        timerTextEdit.replace(2,4,"59");
        }
    
    if (Integer.parseInt(timerTextEdit.substring(4,6)) > 59) {
        timerTextEdit.replace(4,6,"59");
        }
    
    timerInput.setText(timerTextEdit.toString());
    
//    if (timerInput.getText() != timerTextEdit.toString()) {
//        System.out.println("text insertion failed!!\n-----------");
//        System.out.println("current text: " + timerInput.getText());
//        System.out.println("edited text: " + timerTextEdit.toString());
//    }
    }//GEN-LAST:event_timerInputMouseClicked

    private void taskAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskAddButtonActionPerformed
                Task newTask = new Task(startButton);
                newTask.setAlignmentY(Component.TOP_ALIGNMENT);
                
                //TODO: make the 
                taskPanel.add(newTask);
                System.out.println(taskPanel.getClass());

                // Revalidate and repaint the panel to show the new button
                taskPanel.revalidate();
                taskPanel.repaint();
    }//GEN-LAST:event_taskAddButtonActionPerformed

    private void filterGUISetup() {
        Document timerDoc = timerInput.getDocument();
        AbstractDocument doc;
        
        if (timerDoc instanceof AbstractDocument) {
            doc = (AbstractDocument)timerDoc;
            doc.setDocumentFilter(new timerFilter());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudyBomb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudyBomb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudyBomb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudyBomb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form. */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudyBomb().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileExplorer;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JPanel filePanel;
    private javax.swing.JButton fileSearchButton;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JButton taskAddButton;
    private javax.swing.JPanel taskPanel;
    private javax.swing.JScrollPane taskScroll;
    private javax.swing.JLayeredPane taskView;
    private javax.swing.JPanel timerControls;
    private javax.swing.JFrame timerDialog;
    private javax.swing.JLabel timerDisplay;
    private javax.swing.JTextField timerInput;
    private javax.swing.JPanel timerPanel;
    private javax.swing.JLabel timerRuler;
    private javax.swing.JLabel timerUI;
    // End of variables declaration//GEN-END:variables
}
